import express from "express"; import cors from "cors"; import {eq,desc} from "drizzle-orm"; import {z} from "zod";
import {libraryInputSchema,preferencesSchema,vnSummarySchema,type LibraryEntry,type Preferences} from "@afterglow/shared"; import {db} from "./db.js"; import {appSettings,libraryEntries} from "./schema.js"; import {getVn,personalizedVns,searchTags,searchVns} from "./vndb.js"; import {rankRecommendations} from "./recommend.js";
const app=express(); app.use(cors({origin:"http://localhost:5173"})); app.use(express.json({limit:"1mb"}));
function serialize(r:any):LibraryEntry{return {id:r.id,vndbId:r.vndbId,status:r.status,personalRating:r.personalRating,favorite:Boolean(r.favorite),progress:r.progress,notes:r.notes,startedAt:r.startedAt,completedAt:r.completedAt,vn:JSON.parse(r.vnJson),createdAt:r.createdAt,updatedAt:r.updatedAt};}
app.get("/api/health",(_,res)=>res.json({ok:true}));
app.get("/api/vndb/search",async(req,res,next)=>{try{const q=z.string().max(100).default("").parse(req.query.q);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const platform=z.enum(["win","lin","mac","and","ios","swi","ps4","ps5"]).optional().parse(req.query.platform||undefined);const length=z.coerce.number().int().min(1).max(5).optional().parse(req.query.length||undefined);const year=z.coerce.number().int().min(1980).max(new Date().getFullYear()).optional().parse(req.query.year||undefined);const rating=z.coerce.number().int().min(1).max(10).optional().parse(req.query.rating||undefined);const sort=z.enum(["rating","released","votecount","title"]).default("rating").parse(req.query.sort);res.json(await searchVns({q,page,platform,length,year,rating,sort}));}catch(e){next(e)}});
app.get("/api/vndb/tags",async(req,res,next)=>{try{const q=z.string().max(100).default("").parse(req.query.q);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const category=z.enum(["cont","ero","tech"]).optional().parse(req.query.category||undefined);res.json(await searchTags(q,page,category));}catch(e){next(e)}});
app.get("/api/vndb/vn/:id",async(req,res,next)=>{try{const id=z.string().regex(/^v\d+$/).parse(req.params.id);const vn=await getVn(id);if(!vn)return res.status(404).json({error:"Visual novel not found",code:"NOT_FOUND"});res.json(vn);}catch(e){next(e)}});
app.get("/api/library",async(_,res)=>res.json((await db.select().from(libraryEntries).orderBy(desc(libraryEntries.updatedAt))).map(serialize)));
app.put("/api/library/:vndbId",async(req,res,next)=>{try{const id=z.string().regex(/^v\d+$/).parse(req.params.vndbId);const input=libraryInputSchema.parse(req.body);const now=new Date().toISOString();await db.insert(libraryEntries).values({vndbId:id,status:input.status,personalRating:input.personalRating,favorite:input.favorite,progress:input.progress,notes:input.notes,startedAt:input.startedAt,completedAt:input.completedAt,vnJson:JSON.stringify(input.vn),createdAt:now,updatedAt:now}).onConflictDoUpdate({target:libraryEntries.vndbId,set:{status:input.status,personalRating:input.personalRating,favorite:input.favorite,progress:input.progress,notes:input.notes,startedAt:input.startedAt,completedAt:input.completedAt,vnJson:JSON.stringify(input.vn),updatedAt:now}});const row=(await db.select().from(libraryEntries).where(eq(libraryEntries.vndbId,id)))[0];res.json(serialize(row));}catch(e){next(e)}});
app.delete("/api/library/:vndbId",async(req,res,next)=>{try{const id=z.string().regex(/^v\d+$/).parse(req.params.vndbId);await db.delete(libraryEntries).where(eq(libraryEntries.vndbId,id));res.status(204).end();}catch(e){next(e)}});
const defaults:Preferences={tagPreferences:[],preferredLengths:[],preferredPlatforms:[],useSpoilerTagsInRecommendations:false,completed:false};
function readPreferences(value?:string):Preferences{if(!value)return defaults;const old=JSON.parse(value);if(!old.tagPreferences)old.tagPreferences=[...(old.preferredTags??[]).map((name:string)=>({id:name,name,weight:2})),...(old.avoidedTags??[]).map((name:string)=>({id:name,name,weight:-3}))];return preferencesSchema.parse(old)}
app.get("/api/preferences",async(_,res)=>{const row=(await db.select().from(appSettings).where(eq(appSettings.key,"preferences")))[0];res.json(readPreferences(row?.value))});
app.put("/api/preferences",async(req,res,next)=>{try{const p=preferencesSchema.parse(req.body);await db.insert(appSettings).values({key:"preferences",value:JSON.stringify(p)}).onConflictDoUpdate({target:appSettings.key,set:{value:JSON.stringify(p)}});res.json(p);}catch(e){next(e)}});
app.get("/api/recommendations",async(_,res,next)=>{try{const rows=(await db.select().from(libraryEntries)).map(serialize);const prefRow=(await db.select().from(appSettings).where(eq(appSettings.key,"preferences")))[0];const prefs=readPreferences(prefRow?.value);const positiveIds=prefs.tagPreferences.filter(p=>p.weight>0&&/^g\d+$/.test(p.id)).sort((a,b)=>b.weight-a.weight).map(p=>p.id);res.json(rankRecommendations(await personalizedVns(positiveIds,prefs.useSpoilerTagsInRecommendations),rows,prefs));}catch(e){next(e)}});
app.post("/api/recommendations/score",async(req,res,next)=>{try{const vns=z.array(vnSummarySchema).max(30).parse(req.body?.vns);const rows=(await db.select().from(libraryEntries)).map(serialize);const prefRow=(await db.select().from(appSettings).where(eq(appSettings.key,"preferences")))[0];res.json(rankRecommendations(vns,rows,readPreferences(prefRow?.value),false,vns.length));}catch(e){next(e)}});
app.get("/api/recommendations/:id",async(req,res,next)=>{try{const id=z.string().regex(/^v\d+$/).parse(req.params.id);const vn=await getVn(id);if(!vn)return res.status(404).json({error:"Visual novel not found",code:"NOT_FOUND"});const rows=(await db.select().from(libraryEntries)).map(serialize);const prefRow=(await db.select().from(appSettings).where(eq(appSettings.key,"preferences")))[0];const scored=rankRecommendations([vn],rows,readPreferences(prefRow?.value),false)[0];res.json(scored);}catch(e){next(e)}});
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({error:err.issues[0]?.message??"Invalid request",code:"VALIDATION_ERROR"});res.status(err.status===429?429:502).json({error:err.message??"Something went wrong",code:err.status===429?"RATE_LIMITED":"UPSTREAM_ERROR"});});
app.listen(3001,()=>console.log("Afterglow API at http://localhost:3001"));
