import {describe,expect,it} from "vitest";
import {rankRecommendations} from "./recommend.js";
import type {LibraryEntry,Preferences,VnSummary} from "@afterglow/shared";

const vn=(id:string,tags:{id:string;name:string;rating?:number;spoiler?:number}[],rating=80,voteCount=500):VnSummary=>({id,title:id,imageUrl:null,imageSexual:0,imageViolence:0,released:null,rating,voteCount,length:3,platforms:["win"],tags:tags.map(t=>({...t,rating:t.rating??3,spoiler:t.spoiler??0}))});
const prefs:Preferences={tagPreferences:[{id:"g1",name:"Mystery",weight:3}],preferredLengths:[3],preferredPlatforms:["win"],useSpoilerTagsInRecommendations:false,completed:true};
const entry=(story:VnSummary,overrides:Partial<LibraryEntry>={}):LibraryEntry=>({id:1,vndbId:story.id,vn:story,status:"completed",personalRating:9,favorite:true,progress:100,notes:"",startedAt:null,completedAt:null,createdAt:"",updatedAt:"",...overrides});

describe("rankRecommendations",()=>{
 it("prefers matching themes and excludes owned titles",()=>{const ranked=rankRecommendations([vn("v1",[{id:"g2",name:"Horror"}]),vn("v2",[{id:"g1",name:"Mystery"}])],[],prefs);expect(ranked[0].vn.id).toBe("v2");expect(ranked[0].reasons.join(" ")).toContain("Mystery")});
 it("provides a quality-led but confidence-muted fallback",()=>{const empty={...prefs,tagPreferences:[],preferredLengths:[],preferredPlatforms:[],completed:false};const high=rankRecommendations([vn("v1",[],90,10000)],[],empty)[0];const low=rankRecommendations([vn("v2",[],60,10)],[],empty)[0];expect(high.matchPercent).toBeGreaterThan(low.matchPercent);expect(high.matchPercent).toBeLessThan(65);expect(low.matchPercent).toBeGreaterThan(40)});
 it("penalizes avoided tags instead of saturating matches",()=>{const tailored={...prefs,tagPreferences:[...prefs.tagPreferences,{id:"g3",name:"Gore",weight:-3}]};const clean=rankRecommendations([vn("v1",[{id:"g1",name:"Mystery"}]),vn("v2",[{id:"g1",name:"Mystery"},{id:"g3",name:"Gore"}])],[],tailored);expect(clean[0].vn.id).toBe("v1");expect(clean[0].matchPercent-clean[1].matchPercent).toBeGreaterThan(15);expect(clean[0].matchPercent).toBeLessThan(95)});
 it("learns from ratings, favorites, and dropped titles",()=>{const mystery=vn("v10",[{id:"g1",name:"Mystery"}]);const gore=vn("v11",[{id:"g3",name:"Gore"}]);const empty={...prefs,tagPreferences:[],preferredLengths:[],preferredPlatforms:[]};const ranked=rankRecommendations([vn("v1",[{id:"g1",name:"Mystery"}]),vn("v2",[{id:"g3",name:"Gore"}])],[entry(mystery),entry(gore,{id:2,vndbId:"v11",favorite:false,personalRating:2,status:"dropped"})],empty);expect(ranked[0].vn.id).toBe("v1");expect(ranked[0].reasons.join(" ")).toContain("favorites and ratings")});
 it("produces a useful spread without ceiling bunching",()=>{const rich:Preferences={tagPreferences:[{id:"g1",name:"Mystery",weight:3},{id:"g2",name:"Romance",weight:1},{id:"g3",name:"Gore",weight:-3}],preferredLengths:[3],preferredPlatforms:["win"],useSpoilerTagsInRecommendations:false,completed:true};const ranked=rankRecommendations([vn("v1",[{id:"g1",name:"Mystery"},{id:"g2",name:"Romance"}],90,10000),vn("v2",[{id:"g1",name:"Mystery"}],75,500),vn("v3",[{id:"g4",name:"Comedy"}],80,1000),vn("v4",[{id:"g3",name:"Gore"}],85,5000)],[],rich);const scores=ranked.map(x=>x.matchPercent);expect(Math.max(...scores)).toBeLessThan(95);expect(Math.max(...scores)-Math.min(...scores)).toBeGreaterThan(25);expect(new Set(scores).size).toBe(4)});
 it("uses spoiler tags only when opted in and never names them in explanations",()=>{const hidden=vn("v1",[{id:"g1",name:"Mystery",spoiler:2}]);const plain=vn("v2",[]);const safe=rankRecommendations([hidden,plain],[],prefs,false,2);expect(safe.find(x=>x.vn.id==="v1")?.matchPercent).toBe(safe.find(x=>x.vn.id==="v2")?.matchPercent);const privateResults=rankRecommendations([hidden,plain],[],{...prefs,useSpoilerTagsInRecommendations:true},false,2);expect(privateResults.find(x=>x.vn.id==="v1")!.matchPercent).toBeGreaterThan(privateResults.find(x=>x.vn.id==="v2")!.matchPercent);expect(privateResults.find(x=>x.vn.id==="v1")!.reasons.join(" ")).not.toContain("Mystery")});
});
